spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/gymcrm
    username: gymuser
    password: gympass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect