spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gymcrm
    username: gymuser
    password: gympass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

data:
  source: DATABASE